# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        deep learning: 1
        machine learning: 1
        recognition: 1
        segmentation: 1
        detection: 1
        action: 1
        image: 1
        video: 1
        retrieval: 1
        

# 通知の閾値
score_threshold: 1
