# arxivの学問領域の指定
subject: 'cat:cs.CV'

# 検索キーワード
keywords:
        action: 1
        image: 1
        video: 1
        deep learning: 1
        machine learning: 1
        

# 通知の閾値
score_threshold: 0
